### Order Saga Test Requests
###
### Run infrastructure and services first -> docker compose up --build -d
### Kafka UI: http://localhost:8085
### Main API:
@orderBaseUrl = http://localhost:8081

### Known inventory seed data assumed by the project
### for test:
### SKU 11111111-1111-1111-1111-111111111111 has 10 stock.
### SKU 11111111-1111-1111-2222-111111111111 has 20 units.
###
### Payment simulation rules assumed by FakePaymentAuthorizer:
### paymentMethodId starts with 11111111 -> authorized
### paymentMethodId starts with 22222222 -> business failure
### paymentMethodId starts with 33333333 -> technical failure, retry, then DLT


### 1. Happy path
### Expected final flow:
### POST /orders:
###      OrderCreated -> InventoryReserved -> PaymentRequested -> PaymentAuthorized  => order status = CONFIRMED
### Expected final order status: CONFIRMED
POST {{orderBaseUrl}}/orders
Content-Type: application/json
X-Correlation-Id: aaaaaaaa-1111-2222-3333-aaaaaaaaaaaa

{
  "requestId": "10000000-0000-0000-0000-000000000001",
  "checkoutId": "20000000-0000-0000-0000-000000000001",
  "customerId": "30000000-0000-0000-0000-000000000001",
  "paymentMethodId": "11111111-0000-0000-0000-000000000001",
  "currency": "DKK",
  "totalAmount": 50.00,
  "items": [
    {
      "skuId": "11111111-1111-1111-1111-111111111111",
      "productName": "Demo Product A",
      "quantity": 2,
      "unitPrice": 25.00,
      "itemTotalPrice": 50.00
    }
  ]
}


### 2. Duplicate create order request
### Send exactly the same requestId as test 1.
### Expected :
### No new order / no new OrderCreated outbox event / response duplicate = true
POST {{orderBaseUrl}}/orders
Content-Type: application/json
X-Correlation-Id: aaaaaaaa-1111-2222-3333-aaaaaaaaaaab

{
  "requestId": "10000000-0000-0000-0000-000000000001",
  "checkoutId": "20000000-0000-0000-0000-000000000001",
  "customerId": "30000000-0000-0000-0000-000000000001",
  "paymentMethodId": "11111111-0000-0000-0000-000000000001",
  "currency": "DKK",
  "totalAmount": 50.00,
  "items": [
    {
      "skuId": "11111111-1111-1111-1111-111111111111",
      "productName": "Demo Product A",
      "quantity": 2,
      "unitPrice": 25.00,
      "itemTotalPrice": 50.00
    }
  ]
}


### 3. Inventory business failure: not enough stock
### Expected flow:
### POST /orders :
###    OrderCreated -> InventoryReservationFailed  => order status= CANCELLED
POST {{orderBaseUrl}}/orders
Content-Type: application/json
X-Correlation-Id: aaaaaaaa-1111-2222-3333-aaaaaaaaaaac

{
  "requestId": "10000000-0000-0000-0000-000000000002",
  "checkoutId": "20000000-0000-0000-0000-000000000002",
  "customerId": "30000000-0000-0000-0000-000000000002",
  "paymentMethodId": "11111111-0000-0000-0000-000000000002",
  "currency": "DKK",
  "totalAmount": 470.00,
  "items": [
    {
      "skuId": "11111111-1111-1111-1111-111111111111",
      "productName": "Demo Product Low Stock",
      "quantity": 11,
      "unitPrice": 20.00,
      "itemTotalPrice": 220.00
    },
    {
      "skuId": "11111111-1111-1111-2222-111111111111",
      "productName": "Demo Product Low Stock",
      "quantity": 5,
      "unitPrice": 50.00,
      "itemTotalPrice": 250.00
    }
  ]
}


### 4. Inventory business failure: SKU not found
### Expected  flow:
### POST /orders :
###     OrderCreated -> InventoryReservationFailed  => order status= CANCELLED
POST {{orderBaseUrl}}/orders
Content-Type: application/json
X-Correlation-Id: aaaaaaaa-1111-2222-3333-aaaaaaaaaaad

{
  "requestId": "10000000-0000-0000-0000-000000000003",
  "checkoutId": "20000000-0000-0000-0000-000000000003",
  "customerId": "30000000-0000-0000-0000-000000000003",
  "paymentMethodId": "11111111-0000-0000-0000-000000000003",
  "currency": "DKK",
  "totalAmount": 10.00,
  "items": [
    {
      "skuId": "99999999-9999-9999-9999-999999999999",
      "productName": "Unknown Product",
      "quantity": 1,
      "unitPrice": 10.00,
      "itemTotalPrice": 10.00
    }
  ]
}


### 5. Payment business failure and compensation : card declined
### Payment method starts with 22222222.
### Expected flow:
### POST /orders
###     OrderCreated -> InventoryReserved -> PaymentRequested -> PaymentFailed
###     -> InventoryReleaseRequested -> InventoryReleased
###      => order status= CANCELLED and inventory reservation status= RELEASED
POST {{orderBaseUrl}}/orders
Content-Type: application/json
X-Correlation-Id: aaaaaaaa-1111-2222-3333-aaaaaaaaaaae

{
  "requestId": "10000000-0000-0000-0000-000000000004",
  "checkoutId": "20000000-0000-0000-0000-000000000004",
  "customerId": "30000000-0000-0000-0000-000000000004",
  "paymentMethodId": "22222222-0000-0000-0000-000000000004",
  "currency": "DKK",
  "totalAmount": 25.00,
  "items": [
    {
      "skuId": "11111111-1111-1111-1111-111111111111",
      "productName": "Demo Product A",
      "quantity": 1,
      "unitPrice": 25.00,
      "itemTotalPrice": 25.00
    }
  ]
}


### 6. Payment business failure (amount exceeds test authorization limit) and compensation
### Expected flow:
### POST /orders
###     OrderCreated -> InventoryReserved -> PaymentRequested -> PaymentFailed
###     -> InventoryReleaseRequested -> InventoryReleased
###      => order status= CANCELLED and inventory reservation status= RELEASED
POST {{orderBaseUrl}}/orders
Content-Type: application/json
X-Correlation-Id: aaaaaaaa-1111-2222-3333-aaaaaaaaaaaf

{
  "requestId": "10000000-0000-0000-0000-000000000005",
  "checkoutId": "20000000-0000-0000-0000-000000000005",
  "customerId": "30000000-0000-0000-0000-000000000005",
  "paymentMethodId": "11111111-0000-0000-0000-000000000005",
  "currency": "DKK",
  "totalAmount": 1200.00,
  "items": [
    {
      "skuId": "11111111-1111-1111-1111-111111111111",
      "productName": "Demo Product A",
      "quantity": 1,
      "unitPrice": 1200.00,
      "itemTotalPrice": 1200.00
    }
  ]
}


### 7. Payment technical failure
### Payment method starts with 33333333.
### Expected flow:
### POST /orders
###     OrderCreated -> InventoryReserved -> PaymentRequested
###     payment-service throws technical failure => transaction rolls back, retries, then DLT.
###     => order status remains PAYMENT_PENDING.
###     => inventory reservation remains RESERVED.
###  This is correct because technical failure is not a business decline.
POST {{orderBaseUrl}}/orders
Content-Type: application/json
X-Correlation-Id: aaaaaaaa-1111-2222-3333-aaaaaaaaaaba

{
  "requestId": "10000000-0000-0000-0000-000000000006",
  "checkoutId": "20000000-0000-0000-0000-000000000006",
  "customerId": "30000000-0000-0000-0000-000000000006",
  "paymentMethodId": "33333333-0000-0000-0000-000000000006",
  "currency": "DKK",
  "totalAmount": 25.00,
  "items": [
    {
      "skuId": "11111111-1111-1111-1111-111111111111",
      "productName": "Demo Product A",
      "quantity": 1,
      "unitPrice": 25.00,
      "itemTotalPrice": 25.00
    }
  ]
}


### 8. Checkout snapshot validation failure: item total does not match quantity * unit price
### Expected:
### Request rejected by order-service : HTTP 400.
### Expected side effect: No order and no outbox event.
POST {{orderBaseUrl}}/orders
Content-Type: application/json
X-Correlation-Id: aaaaaaaa-1111-2222-3333-aaaaaaaaaabb

{
  "requestId": "10000000-0000-0000-0000-000000000007",
  "checkoutId": "20000000-0000-0000-0000-000000000007",
  "customerId": "30000000-0000-0000-0000-000000000007",
  "paymentMethodId": "11111111-0000-0000-0000-000000000007",
  "currency": "DKK",
  "totalAmount": 25.00,
  "items": [
    {
      "skuId": "11111111-1111-1111-1111-111111111111",
      "productName": "Demo Product A",
      "quantity": 2,
      "unitPrice": 25.00,
      "itemTotalPrice": 25.00
    }
  ]
}


### 9. Checkout snapshot validation failure: totalAmount does not match sum(itemTotalPrice)
### Expected:
### Request rejected by order-service : : HTTP 400
### Expected side effect:  No order and no outbox event.
POST {{orderBaseUrl}}/orders
Content-Type: application/json
X-Correlation-Id: aaaaaaaa-1111-2222-3333-aaaaaaaaaabc

{
  "requestId": "10000000-0000-0000-0000-000000000008",
  "checkoutId": "20000000-0000-0000-0000-000000000008",
  "customerId": "30000000-0000-0000-0000-000000000008",
  "paymentMethodId": "11111111-0000-0000-0000-000000000008",
  "currency": "DKK",
  "totalAmount": 999.00,
  "items": [
    {
      "skuId": "11111111-1111-1111-1111-111111111111",
      "productName": "Demo Product A",
      "quantity": 1,
      "unitPrice": 25.00,
      "itemTotalPrice": 25.00
    }
  ]
}


### 10. Request validation failure: missing requestId
### Expected:
### Bean validation rejects request.
### Expected side effect: No order and no outbox event.
POST {{orderBaseUrl}}/orders
Content-Type: application/json
X-Correlation-Id: aaaaaaaa-1111-2222-3333-aaaaaaaaaabd

{
  "checkoutId": "20000000-0000-0000-0000-000000000009",
  "customerId": "30000000-0000-0000-0000-000000000009",
  "paymentMethodId": "11111111-0000-0000-0000-000000000009",
  "currency": "DKK",
  "totalAmount": 25.00,
  "items": [
    {
      "skuId": "11111111-1111-1111-1111-111111111111",
      "productName": "Demo Product A",
      "quantity": 1,
      "unitPrice": 25.00,
      "itemTotalPrice": 25.00
    }
  ]
}


### 11. Request validation failure: invalid item quantity
### Expected:
### Bean validation rejects request.
### Expected side effect:
### No order and no outbox event.
POST {{orderBaseUrl}}/orders
Content-Type: application/json
X-Correlation-Id: aaaaaaaa-1111-2222-3333-aaaaaaaaaabe

{
  "requestId": "10000000-0000-0000-0000-000000000010",
  "checkoutId": "20000000-0000-0000-0000-000000000010",
  "customerId": "30000000-0000-0000-0000-000000000010",
  "paymentMethodId": "11111111-0000-0000-0000-000000000010",
  "currency": "DKK",
  "totalAmount": 25.00,
  "items": [
    {
      "skuId": "11111111-1111-1111-1111-111111111111",
      "productName": "Demo Product A",
      "quantity": -2,
      "unitPrice": 25.00,
      "itemTotalPrice": 25.00
    }
  ]
}


### 12. Duplicate SKU lines in one order
### Expected:
###   order-service stores two order_items
###   inventory-service groups quantities by SKU quantities before locking
###   stock reservation uses summed quantity
###   happy path if stock is available
### => Expected final order status: CONFIRMED if enough stock remains
POST {{orderBaseUrl}}/orders
Content-Type: application/json
X-Correlation-Id: aaaaaaaa-1111-2222-3333-aaaaaaaaaabf

{
  "requestId": "10000000-0000-0000-0000-000000000011",
  "checkoutId": "20000000-0000-0000-0000-000000000011",
  "customerId": "30000000-0000-0000-0000-000000000011",
  "paymentMethodId": "11111111-0000-0000-0000-000000000011",
  "currency": "DKK",
  "totalAmount": 175.00,
  "items": [
    {
      "skuId": "11111111-1111-1111-1111-111111111111",
      "productName": "Demo Product A",
      "quantity": 1,
      "unitPrice": 25.00,
      "itemTotalPrice": 25.00
    },
    {
      "skuId": "11111111-1111-1111-2222-111111111111",
      "productName": "Demo Product B",
      "quantity": 2,
      "unitPrice": 50.00,
      "itemTotalPrice": 100.00
    },
    {
      "skuId": "11111111-1111-1111-1111-111111111111",
      "productName": "Demo Product A",
      "quantity": 2,
      "unitPrice": 25.00,
      "itemTotalPrice": 50.00
    }
  ]
}





