### Normal Request  -> Should return Status:201
POST http://localhost:8081/orders
Content-Type: application/json

{
  "requestId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
  "checkoutId": "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
  "customerId": "cccccccc-cccc-cccc-cccc-cccccccccccc",
  "paymentMethodId": "11111111-1111-1111-1111-111111111111",
  "currency": "DKK",
  "totalAmount": 200.00,
  "items": [
    {
      "skuId": "11111111-1111-1111-1111-111111111111",
      "productName": "Demo Product A",
      "quantity": 4,
      "unitPrice": 25.00,
      "itemTotalPrice": 100.00
    },
    {
      "skuId": "11111111-2222-1111-1111-111111111111",
      "productName": "Demo Product B",
      "quantity": 2,
      "unitPrice": 50.00,
      "itemTotalPrice": 100.00
    }
  ]
}

### Empty CreateOrderRequest -> Should return Status:400
POST http://localhost:8081/orders
Content-Type: application/json

{
  "requestId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
  "checkoutId": "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
  "customerId": "cccccccc-cccc-cccc-cccc-cccccccccccc",
  "paymentMethodId": "11111111-1111-1111-1111-111111111111",
  "currency": "DKK",
  "totalAmount": 200.00,
  "items": []
}


### Null customerId and quantity for an item -> Should return Status:400
POST http://localhost:8081/orders
Content-Type: application/json

{
  "requestId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
  "checkoutId": "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",

  "paymentMethodId": "11111111-1111-1111-1111-111111111111",
  "currency": "DKK",
  "totalAmount": 200.00,
  "items": [
    {
      "skuId": "11111111-1111-1111-1111-111111111111",
      "productName": "Demo Product A",

      "unitPrice": 25.00,
      "itemTotalPrice": 100.00
    },
    {
      "skuId": "11111111-2222-1111-1111-111111111111",
      "productName": "Demo Product B",
      "quantity": 2,
      "unitPrice": 50.00,
      "itemTotalPrice": 100.00
    }
  ]
}