### Normal Request  -> Should return Status:201
POST http://localhost:8081/orders
Content-Type: application/json

{
  "items": [
    {
      "skuId": "22331111-1111-2222-1111-111111111111",
      "quantity": 12
    },
    {
      "skuId": "33111111-2222-1111-2222-111111111111",
      "quantity": 5
    }
  ]
}

### Empty CreateOrderRequest -> Should return Status:400
POST http://localhost:8081/orders
Content-Type: application/json

{
  "items": []
}

### Null quantity for an item -> Should return Status:400
POST http://localhost:8081/orders
Content-Type: application/json

{
  "items": [
    {
      "skuId": "11111111-1111-1111-1111-111111111111",
      "quantity": 2
    },
    {
      "skuId": "11111111-1111-1111-2222-111111111111"
    }
    ]
}