server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: payment-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5435/paymentdb}
    username: ${DB_USERNAME:user3}
    password: ${DB_PASSWORD:pass3}

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
    producer:
      properties:
        acks: all

app:
  kafka:
    topics:
      payment-requested: payment.requested.v1
      payment-authorized: payment.authorized.v1
      payment-failed: payment.failed.v1

  outbox:
    claim-limit: 20
    max-retries: 10
    fixed-delay-ms: 5000
    recovery-delay-ms: 60000

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} correlationId=%X{correlationId} eventId=%X{eventId} eventType=%X{eventType} causationId=%X{causationId} source=%X{source} orderId=%X{orderId} requestId=%X{requestId} - %msg%n"
  level:
    root: INFO
    com.shirin: INFO
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    org.springframework.kafka: WARN
    org.apache.kafka: WARN
    org.hibernate: WARN