
server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5433/orderdb
    username: user1
    password: pass1

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: order-service
      auto-offset-reset: earliest
    producer:
      properties:
        acks: all

app:
  kafka:
    topics:
      order-created: order.created.v1
  outbox:
    claim-limit: 1
    max-retries: 10
    fixed-delay-ms: 20000
    recovery-delay-ms: 60000